JonPawelko/porcfestassassin

app.js

Second test commit - implement a test feature

---

lib/db.js
package-lock.json
package.json
routes/assassin.js

Simple change to location of credentials file.  Changed dir name from gitignore just in case it messages with git.

Replaced gitignore in path to credentials

---

routes/assassin.js
views/home.ejs

Updated credentials file separately.  Home and assassin router updated.  Immediately check if player is admin, if yes, show admin features, else show regular player features.  Admin is now a prepped player with admin email in db.

Updates to separate admin vs regular players

---

routes/assassin.js

Created a new function validateTeamName to allow numbers in a team name.

Allow numbers in team names

---

views/adminFeatures.ejs

Admin only changes.  Various spacing to admin page, added buttons.

Added logout and view rules buttons and some spacing

---

routes/assassin.js
views/adminFeatures.ejs
views/adminPlayerList.ejs

Added a celeb player checkbox for admin to filter on.  Also fixed a bug on Search For Team where the captain player code wasn't being returned.

Added celeb player search box for admin

---

views/landing2.ejs

Minor spacing updates

---

views/adminPlayerHome.ejs

The Player Home page within the Admin app now has the team name and the team code is a link.  Click on the link to go to the Team Home page within Admin.

Player Admin home added team link

---

views/landing.ejs

Added more info on the game.  Want to make it more friendly looking for when snoops coming along.

Added more info to Landing page

---

lib/db.js
routes/assassin.js

Hey Jon.  I coded this feature.  Here are the details.  Here is why.

Demo changes with Max - no logic change

---

views/adminBulkPictureApprove.ejs
views/adminPlayerHome.ejs

Fixed bug on "one" and "more" flags for photo review.  I added constants in the app.js "one" and "more", but they started uppercase in the .ejs files.  Changed all to lowercase.

Fixed admin photo approve bug

---

routes/assassin.js

test feature only

---

lib/db.js

Hey Jon,
Check out my coding change

test with Jon 2

---

app.js
lib/db.js
routes/assassin.js

Changed db name from 'assassin-demo1' to 'assassin'.  Required changes in db and assassin.js.  Also started creating global environment variables to ease process of switching between developers and environments.

Changed db name, added global env vars

---

.gitignore

Doing one change at a time to make sure the add to gitignore works.

Only added personal directory to gitignore

---

views/adminEditPlayerData.ejs
views/contactAdmin.ejs
views/editPlayerPhone.ejs
views/landing2.ejs

Added a phone number format helper below the Input box on all 4 screens with phone edits.

Added xxx-xxx-xxxx phone format helper

---

routes/assassin.js
views/adminFeatures.ejs

Added feature to Admin to check the integrity of the database.  First batch of checks here, more to come.

First clean data check update

---

app.js
routes/assassin.js
views/cronScheduler.ejs

Removed last kill of day contest as an option.  Probably too annoying to code now.  Also updated text label showing the current running contest.

Deleted a contest - Updated running contest label

---

routes/assassin.js
views/home.ejs
views/viewHistory.ejs

Button on Home Page now allows player to view the history of important team events and also player messages to admin.  Re-used rules page formatting.

Added view team history feature

---

app.js
views/errorMessagePage.ejs

Fix scenario where 1 team remains live.  That team gets put into Waiting until a new team comes along.  Therefore, all moves into the Waiting Area now check if there is no chain and 1 other team in waiting.  If so, those 2 teams go live.  Updates to several mysql stored procedures.  See spreadsheet.

Minor event add to error and app js - Many changes in mysql

---

app.js
public/javascripts/utilities.js
views/adminCreatePrepTemplates.ejs
views/adminFeatures.ejs

Added game status to top of Admin screen.  Moved admin buttons around so that drop bomb was its own form and could have a Confirm Choice before bombing.  Also added a Home button to create templates page.

Few Minor Admin Bugs - game status, confirm bomb

---

routes/assassin.js
views/captainFeatures.ejs
views/landing.ejs
views/rules.ejs

Cleaned up some text, noticed a few events were missing from Team History feature.  Minor update to rules around buying back in on the site.

Minor wording updates - team history case update

---

views/adminActivateTeamTemplate.ejs
views/contactAdmin.ejs
views/cronScheduler.ejs
views/editPlayerPhone.ejs

Added 4 Home buttons – Edit phone page, contact admin, cron scheduler, and activate prepped team pages.

Added 4 home buttons

---

views/rules.ejs

Bottom of rules page.  As pre paypal guidelines.

Added privacy policy and paypal use link

---

app.js
routes/assassin.js
views/captainFeatures.ejs
views/paypalInitialRegular.ejs
views/rules.ejs

Added new personal environment variable for paypal.  Either off, test, or production.  Tested each.  Test = sandbox.

Paypal prod env updates

---

views/paypalInitialCeleb.ejs
views/paypalRebuy.ejs

Applied the same changes made to regular paypal initial buy to celeb buy in and rebuy.

Finished paypal updates celebs and rebuy

---

public/javascripts/utilities.js
views/home.ejs
views/landing.ejs

3 updates - 1) Changed Shift-l to Control-l to logout (that's a little L).  2) Added minor wording change to Landing page... pay now or later... 3) Show no shift date for new players instead of the default 2001-01 date we're using in the db.

3 minor updates

---

routes/assassin.js
views/adminFeatures.ejs
views/freeAgentFeatures.ejs
views/liveTeamFeatures.ejs
views/paidTeamFeatures.ejs
views/picsApprovedTeamFeatures.ejs
views/quitTeamFeatures.ejs
views/registeredTeamFeatures.ejs
views/waitingTeamFeatures.ejs

Batch of 3 minor changes: 1) Removed the return that was in the cron node start and end functions, was preventing any code from running, 2) removed the force schedule manual function from admin, we'll rely on the cron job, and 3) Added some extra space to the blank area under Game Over message (cosmetic only)

3 minor changes

---

app.js

Removed old cron scripts file not in use, now needed to remove reference to it from app.js

Removed ref to old file

---

app.js
routes/assassin.js

Twilio is now a global setting in the personal settings file so you can turn it on and off without updating the code.  All code now checks the global variable before sending a text.

Added twilio setting

---

routes/assassin.js

Cleaned out the res in all cron function error clauses.  No res down there in those side functions.  Also morning cron had an immediate return.  Not fully tested, want to get it in before applying other fixes.

Morning cron function fixes

---

views/home.ejs

Player celeb status was already being sent to home page, now added it to the Player Data section.

Added celeb status to player data

---

routes/assassin.js

Minor fix to cron photo logic.

Cron photo rpt bug fix

---

routes/assassin.js

Updated code to now update the db when you run cron scripts for start game, end game, morning start, and night end.  Whatever admin enters is updated to the db.

Updating Game table on cron runs

---

bin/www

Changed www file in bin to use https

https initial test

---

bin/www

Quick https undo fix

---

routes/assassin.js
views/adminFeatures.ejs
views/adminTeamListNotPaid.ejs

Added admin button to show all teams that have registered, but not paid.  Ability to then send all a message like, "Admin will be at check in from Noon - 12:30 today to pay up".  Only works for lists of teams right now.  need to add ability to send 1 message to 1 team captain.

Admin report not paid

---

routes/assassin.js
views/adminPlayerHome.ejs
views/adminTeamListNotPaid.ejs

Admin's Player home page now has ability to sent player a text if they have their phone number in the db

Admin send message to player

---

app.js
public/javascripts/utilities.js
routes/assassin.js

minor tweaks, Removed confirm_force_shift, done auto now.  Removed old comments.

minor comment removal

---

views/adminTeamHome.ejs

Hey Jon,
I fixed the link in the Admin search for team where the captain of the team has a link to the player

Fixed link in Admin search for team

---

routes/assassin.js
views/landing.ejs
views/landing2.ejs
views/rules.ejs

Added View Rules button on landing page to enable prospective players to learn about game.  Also tweaked wording in a few places.

Added external rules page

---

public/stylesheets/custom.css

Card header color now matches blue bootstrap buttons, white font

Card header color and font

---

routes/assassin.js
views/adminFeatures.ejs
views/adminPlayersWithNoTeam.ejs

Button added to Admin Features for checking players with no teams.  Incomplete update, next branch has final fix.  forgot to check logout button.

Admin report players no team

---

views/adminFeatures.ejs
views/captainFeatures.ejs
views/errorMessagePage.ejs
views/home.ejs
views/landing2.ejs
views/managePicture.ejs
views/palPalSuccess.ejs

Fixed last branch.  Added logout button.  Also fixed type in several files.  seemed to work anyway.

textPlayers fix typo fix

---

views/rules.ejs

Rules wording only

---

routes/assassin.js
views/createTeamFeatures.ejs
views/freeAgentFeatures.ejs
views/home.ejs
views/joinTeamFeatures.ejs
views/landing.ejs
views/landing2.ejs
views/liveTeamFeatures.ejs

Multiple updates post Quill testing event:
- Re-org'd instructions on several pages.
- Updated button names in a few places
- Statistics Team Kills bug fix
- My Target's Target changed
- All texts now have a link to the website

Multi changes after testing event

---

views/landing.ejs

Centered bootstrap card home page as test, if fully works will apply to all cards in next update.

Centered home page

---

routes/assassin.js
views/adminActivateTeamTemplate.ejs
views/adminBulkPictureApprove.ejs
views/adminChoosePhoto.ejs
views/adminCreatePrepTemplates.ejs
views/adminEditPlayerData.ejs
views/adminFeatures.ejs
views/adminPlayerHome.ejs
views/adminPlayerList.ejs
views/adminPlayersWithNoTeam.ejs
views/adminTeamHome.ejs
views/adminTeamList.ejs
views/adminTeamListNotPaid.ejs
views/captainFeatures.ejs
views/contactAdmin.ejs
views/cronScheduler.ejs
views/editPlayerPhone.ejs
views/errorMessagePage.ejs
views/freeAgentFeatures.ejs
views/gameStatistics.ejs
views/home.ejs
views/landing2.ejs
views/managePicture.ejs
views/palPalSuccess.ejs
views/rules.ejs
views/viewHistory.ejs

Centered all cards.  Fixed bugs for:
- Team name in lists when no team exists for that player
- Removed Team history button for player with no team
- AdminPlayerHome was buggy if coming from No Team or Not Paid

Centered all cards fixed few bugs

---

routes/assassin.js
views/adminPlayerList.ejs

Admin search on celeb only bug fix
Admin player list extra space when no team
Admin search on non-celeb only
Sorted player and team list (by name)

Admin Search Player bugs

---

routes/assassin.js
views/adminFeatures.ejs

Added search all logic for team

Search all checkbox team

---

app.js
views/home.ejs
views/rules.ejs

Rules wording, one more centered card

Rules update minor bugs

---

routes/assassin.js
views/captainFeatures.ejs

Minor wording update.  Also added "Assassin Alert" to the beginning of every text.  DB update not part of git, but also fixed ability to reject a picture of a player not on a team.

Wording update, text alert update

---

routes/assassin.js

Now check after RPC for a success = 1.  Now can only drop bomb when live (db change).  all other statuses now show error.

Admin error checking on bomb drop

---

app.js
routes/assassin.js
views/adminPlayersWithNoTeam.ejs
views/gameStatistics.ejs
views/home.ejs
views/liveTeamFeatures.ejs
views/paidTeamFeatures.ejs
views/picsApprovedTeamFeatures.ejs
views/quitTeamFeatures.ejs
views/registeredTeamFeatures.ejs
views/rules.ejs
views/waitingTeamFeatures.ejs

Cron scheduling bug
Minor rules wording
Bolded team and individual status
Added Game is live status message to top
Fixed spacing bug in title
Event 2 from Waiting to Live to just Live
Added twilio data to bottom of admin
DB fixes to Test - changes to reject picture function, change to start game rpc return code wrong for insufficient teams.

Many bug fixes and wording tweaks

---

views/landing.ejs

Minor spacing on home page

---

routes/assassin.js
views/landing.ejs
views/rules.ejs

Changed Rules logic.  No longer creating a new window.  No diff between internal and external viewing of rules now.  Use Express / home page route now.

Rules prod bug fix

---

app.js
routes/assassin.js
views/adminFeatures.ejs
views/cronScheduler.ejs

Added cron job to ping the db every minute.  added timestamp to error logs, removed reset db button, fixed spacing of admin search buttons.

db connection ping better logging

---

routes/assassin.js

Added checkIncrementDailyTextCount function to make sure daily text count gets checked and updated.  If no texts were sent, it would never get updated.  Call this function in morning start.

Fixed daily text count bug

---

routes/assassin.js

Added daily text counter checker to start game too, ensure runs once a day

Added text check to start game cron

---

routes/assassin.js
views/adminFeatures.ejs
views/rules.ejs

Texts sent today fix, was always 1 if I didn't send any texts from day before
first names with extra space before or after – clear out in node js before sending to mysql
Add texts sent check to start game cron function too
Broadcast feature – send text to all
Take a break before game starts works, allow return from break any time before game starts or overnight, break overnight ok
rules - Jon – Noon every day for registrations, questions.

May 25 changes several

---

views/rules.ejs

Added rule that captain divides winnings

Added captain rule divide winnings

---

routes/assassin.js
views/adminFeatures.ejs
views/viewChain.ejs

view chain feature

---

views/captainFeatures.ejs
views/rules.ejs

changed wording from take a break to leave pfest

Leave Porcfest 4

---

public/javascripts/utilities.js
views/rules.ejs

wording only associated with breaks and rules - disruptions

wording only

---

views/adminPlayerHome.ejs
views/adminTeamHome.ejs
views/home.ejs
views/landing2.ejs
views/liveTeamFeatures.ejs
views/managePicture.ejs

Added button logic to prevent double clicks where dangerous.  Only a handful of places.  Buttons with "Are you sure..." confirms are not affected.  Validate Kill was the big one that popped up in production once.

Added button logic to stop bad double clicks

---

views/benchFeatures.ejs
views/captainFeatures.ejs
views/home.ejs
views/landing2.ejs
views/managePicture.ejs
views/rules.ejs
views/waitingTeamFeatures.ejs

Updated text and rules for clarity

---

routes/assassin.js

I believe the only code change was the formatting of texts to players, got rid of military time.  I think the texts to only inactive players is done from the db layer

Not sure - no texts to inactive players

---

app.js
routes/assassin.js
views/adminFeatures.ejs
views/adminTeamHome.ejs
views/rules.ejs
views/viewEvents.ejs
views/viewFullStatus.ejs
views/viewRankings.ejs

Multiple changes - 1) moved db pinger to appjs, runs every 10 minutes automatically, 2) Added view events feature, 3) cleaned up view status report a little, 3) commented out most console logs, 4) Added some date stamps to some console logs that are left  5) Minor rules update

Multiple moved pinger view events

---

routes/assassin.js
views/viewFullStatus.ejs

Fixed photo bug, now all photos stored in directory by id.  Also cleaned up all console logs.

Pic bug use id for dir plus console logs
